# Generated by Django 3.1.4 on 2020-12-09 14:25

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
            ],
        ),
        migrations.CreateModel(
            name='VegetationStrata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
            ],
        ),
        migrations.CreateModel(
            name='VegetationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
                ('code_stake', models.CharField(max_length=128, verbose_name='Code Stake')),
                ('width', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Width')),
                ('height', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Height')),
                ('length', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Length')),
                ('drop_height', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Drop height')),
                ('pit_height', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Pit height')),
                ('filling', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Pit height')),
                ('usage', models.TextField(blank=True, help_text='History, details,  ...', verbose_name='Usage')),
                ('material', models.TextField(blank=True, help_text='Materials,  ...', verbose_name='Materials')),
                ('mobility', models.TextField(blank=True, help_text='Mobility,  ...', verbose_name='Mobility')),
                ('state', models.TextField(blank=True, help_text='State,  ...', verbose_name='State')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.worktype', verbose_name='Work type')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
                ('specific_variety', models.TextField(blank=True, help_text='Details,  ...', verbose_name='Specific variety')),
                ('other_information', models.TextField(blank=True, help_text='Class, Age  ...', verbose_name='Other information')),
                ('state', models.TextField(blank=True, help_text='State ...', verbose_name='State')),
                ('stratum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.vegetationstrata', verbose_name='Vegetation Strata')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.vegetationtype', verbose_name='Vegetation type')),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='History, details,  ...', verbose_name='Description')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(spatial_index=False, srid=settings.SRID)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.knowledgetype', verbose_name='Knowledge type')),
                ('vegetation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.vegetation', verbose_name='Vegetation')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.work', verbose_name='Work')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
