# Generated by Django 3.1.6 on 2021-09-14 07:32

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import geotrek.authent.models
import geotrek.zoning.mixins
import georiviere.watershed.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0005_remove_userprofile_language'),
        ('knowledge', '0006_auto_20210817_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_insert', models.DateTimeField(auto_now_add=True, verbose_name='Insertion date')),
                ('date_update', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update date')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('_geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=settings.SRID)),
                ('length', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Length')),
                ('width', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Width')),
                ('height', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Height')),
                ('measure_frequency', models.CharField(blank=True, default='', max_length=200, verbose_name='Measure frequency')),
            ],
            options={
                'verbose_name': 'Follow-up',
                'verbose_name_plural': 'Follow-ups',
            },
            bases=(georiviere.watershed.mixins.WatershedPropertiesMixin, geotrek.zoning.mixins.ZoningPropertiesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FollowUpType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'Follow-up type',
                'verbose_name_plural': 'Follow-up types',
            },
        ),
        migrations.CreateModel(
            name='FollowUpMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('results', models.TextField(verbose_name='Results')),
                ('follow_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.followup', verbose_name='Follow-up')),
            ],
        ),
        migrations.AddField(
            model_name='followup',
            name='followup_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='knowledge.followuptype', verbose_name='Follow-up type'),
        ),
        migrations.AddField(
            model_name='followup',
            name='knowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.knowledge', verbose_name='Knowledge'),
        ),
        migrations.AddField(
            model_name='followup',
            name='structure',
            field=models.ForeignKey(default=geotrek.authent.models.default_structure_pk, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure'),
        ),
    ]
