# Generated by Django 3.1.6 on 2021-10-12 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0011_auto_20211012_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetation',
            name='age_class_diversity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.vegetationageclassdiversity', verbose_name='Age class diversity'),
        ),
        migrations.AlterField(
            model_name='work',
            name='downstream_bank_effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downstream_effect_works', to='knowledge.workbankeffect', verbose_name='Downstream bank effect'),
        ),
        migrations.AlterField(
            model_name='work',
            name='downstream_influence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downstream_effect_works', to='knowledge.workstreaminfluence', verbose_name='Downstream influence'),
        ),
    ]
