# Generated by Django 3.1.14 on 2022-12-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0012_auto_20211012_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetation',
            name='stratas',
            field=models.ManyToManyField(related_name='vegetations', to='knowledge.VegetationStrata', verbose_name='Vegetation Strata'),
        ),
    ]
