# Generated by Django 3.1.14 on 2022-12-13 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0015_remove_vegetation_strata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkBedEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'Work bed effect',
                'verbose_name_plural': 'Work bed effects',
            },
        ),
        migrations.CreateModel(
            name='WorkWaterEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'Work water effect',
                'verbose_name_plural': 'Work water effects',
            },
        ),
        migrations.AddField(
            model_name='work',
            name='downstream_bed_effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downstream_effect_works', to='knowledge.workbedeffect', verbose_name='Downstream bed effect'),
        ),
        migrations.AddField(
            model_name='work',
            name='upstream_bed_effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upstream_effect_works', to='knowledge.workbedeffect', verbose_name='Upstream bed effect'),
        ),
        migrations.AddField(
            model_name='work',
            name='water_effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='knowledge.workwatereffect', verbose_name='Water effect'),
        ),
    ]
