# Generated by Django 3.1.14 on 2022-12-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0016_auto_20221213_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vegetationageclassdiversity',
            options={'ordering': ['label'], 'verbose_name': 'Age class diversity', 'verbose_name_plural': 'Age class diversities'},
        ),
        migrations.AlterModelOptions(
            name='vegetationstate',
            options={'ordering': ['label'], 'verbose_name': 'Vegetation state', 'verbose_name_plural': 'Vegetation states'},
        ),
        migrations.AlterModelOptions(
            name='vegetationstrata',
            options={'ordering': ['label'], 'verbose_name': 'Vegetation strata', 'verbose_name_plural': 'Vegetation stratas'},
        ),
        migrations.AlterModelOptions(
            name='vegetationtype',
            options={'ordering': ['label'], 'verbose_name': 'Vegetation type', 'verbose_name_plural': 'Vegetation types'},
        ),
        migrations.AlterModelOptions(
            name='workbankeffect',
            options={'ordering': ['label'], 'verbose_name': 'Work bank effect', 'verbose_name_plural': 'Work bank effects'},
        ),
        migrations.AlterModelOptions(
            name='workbedeffect',
            options={'ordering': ['label'], 'verbose_name': 'Work bed effect', 'verbose_name_plural': 'Work bed effects'},
        ),
        migrations.AlterModelOptions(
            name='workfishcontinuityeffect',
            options={'ordering': ['label'], 'verbose_name': 'Work fish continuity effect', 'verbose_name_plural': 'Work fish continuity effects'},
        ),
        migrations.AlterModelOptions(
            name='workmaterial',
            options={'ordering': ['label'], 'verbose_name': 'Work material', 'verbose_name_plural': 'Work materials'},
        ),
        migrations.AlterModelOptions(
            name='worksedimenteffect',
            options={'ordering': ['label'], 'verbose_name': 'Work sediment effect', 'verbose_name_plural': 'Work sediment effects'},
        ),
        migrations.AlterModelOptions(
            name='workstate',
            options={'ordering': ['label'], 'verbose_name': 'Work state', 'verbose_name_plural': 'Work states'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'ordering': ['label'], 'verbose_name': 'Work type', 'verbose_name_plural': 'Work types'},
        ),
        migrations.AlterModelOptions(
            name='workwatereffect',
            options={'ordering': ['label'], 'verbose_name': 'Work water effect', 'verbose_name_plural': 'Work water effects'},
        ),
        migrations.AlterField(
            model_name='vegetation',
            name='stratas',
            field=models.ManyToManyField(blank=True, related_name='vegetations', to='knowledge.VegetationStrata', verbose_name='Vegetation Stratas'),
        ),
    ]
