# Generated by Django 3.1.14 on 2023-12-21 09:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0017_auto_20221215_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineFollowup',
            fields=[
                ('uuid', models.TextField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=2154)),
                ('knowledge_uuid', models.TextField(null=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('date', models.DateField(null=True)),
                ('measure_frequency', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('length', models.FloatField(default=0.0, null=True)),
                ('width', models.FloatField(default=0.0, null=True)),
                ('height', models.FloatField(default=0.0, null=True)),
                ('date_insert', models.DateTimeField(null=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('followup_type', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineKnowledge',
            fields=[
                ('uuid', models.TextField(primary_key=True, serialize=False)),
                ('gra_id', models.IntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=2154)),
                ('name', models.TextField(null=True)),
                ('code', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('date_insert', models.DateTimeField(null=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('knowledge_type', models.IntegerField(null=True)),
                ('vegetation_type', models.IntegerField(null=True)),
                ('vegetation_state', models.IntegerField(null=True)),
                ('thickness', models.IntegerField(null=True)),
                ('age_class_diversity', models.IntegerField(null=True)),
                ('specific_diversity', models.IntegerField(null=True)),
                ('other_information', models.TextField(null=True)),
                ('work_type', models.IntegerField(null=True)),
                ('material', models.IntegerField(null=True)),
                ('work_state', models.IntegerField(null=True)),
                ('downstream_bank_effect', models.IntegerField(null=True)),
                ('upstream_bank_effect', models.IntegerField(null=True)),
                ('downstream_influence', models.IntegerField(null=True)),
                ('upstream_influence', models.IntegerField(null=True)),
                ('sediment_effect', models.IntegerField(null=True)),
                ('water_effect', models.IntegerField(null=True)),
                ('upstream_bed_effect', models.IntegerField(null=True)),
                ('downstream_bed_effect', models.IntegerField(null=True)),
                ('fish_continuity_effect', models.IntegerField(null=True)),
                ('usage', models.TextField(null=True)),
                ('width', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('length', models.FloatField(null=True)),
                ('drop_height', models.FloatField(null=True)),
                ('filling', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineKnowledgeVegetationStrata',
            fields=[
                ('uuid', models.TextField(primary_key=True, serialize=False)),
                ('vegetation_strata_id', models.IntegerField(null=True)),
                ('knowledge_uuid', models.TextField(null=True)),
            ],
        ),
    ]
