# Generated by Django 3.1.14 on 2023-12-20 12:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0018_add_offline_knowledge_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineFollowupAttrs',
            fields=[
                ('uuid', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('date', models.DateField(null=True)),
                ('followup_type', models.IntegerField(null=True)),
                ('measure_frequency', models.CharField(max_length=200, null=True)),
                ('knowledge_attrs_uuid', models.TextField()),
                ('description', models.TextField()),
                ('length', models.FloatField(default=0.0, null=True)),
                ('width', models.FloatField(default=0.0, null=True)),
                ('height', models.FloatField(default=0.0, null=True)),
                ('date_insert', models.DateTimeField(null=True)),
                ('date_update', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineFollowupGeom',
            fields=[
                ('uuid', models.TextField(primary_key=True, serialize=False)),
                ('followup_attrs_uuid', models.TextField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=2154)),
            ],
        ),
    ]
