# Generated by Django 3.1.14 on 2023-12-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0018_offlinefollowup_offlineknowledge_offlineknowledgevegetationstrata'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinefollowup',
            name='username',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offlineknowledge',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
