# Generated by Django 3.1.14 on 2023-12-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0019_auto_20231221_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinefollowup',
            name='gra_id',
            field=models.IntegerField(null=True),
        ),
    ]
