# Generated by Django 3.1.6 on 2021-03-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_auto_20210302_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Station profile code')),
                ('label', models.CharField(max_length=200, verbose_name='Station profile label')),
            ],
            options={
                'verbose_name': 'Station profile',
                'verbose_name_plural': 'Station profiles',
            },
        ),
        migrations.AddField(
            model_name='station',
            name='altitude',
            field=models.IntegerField(blank=True, default=0, verbose_name='Altitude'),
        ),
        migrations.AddField(
            model_name='station',
            name='hardness',
            field=models.IntegerField(blank=True, help_text='For physico-chemical station profile', null=True, verbose_name='Hardness'),
        ),
        migrations.AddField(
            model_name='station',
            name='local_influence',
            field=models.CharField(blank=True, choices=[('0', 'Unknown'), ('1', 'Null'), ('2', 'Low water only'), ('3', 'Strong'), ('4', 'High water only')], help_text='For hydrometric station profile', max_length=5, null=True, verbose_name='Local influence'),
        ),
        migrations.AddField(
            model_name='station',
            name='station_profile',
            field=models.ManyToManyField(to='observations.StationProfile', verbose_name='Station profile'),
        ),
    ]
