# Generated by Django 3.1.6 on 2021-03-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0008_auto_20210318_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='local_influence',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Null'), (2, 'Low water only'), (3, 'Strong'), (4, 'High water only')], default=0, help_text='For hydrometric station profile', verbose_name='Local influence'),
        ),
    ]
