# Generated by Django 3.1.6 on 2021-03-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0011_auto_20210329_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='altitude',
        ),
    ]
