# Generated by Django 3.1.6 on 2021-03-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0013_auto_20210330_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='definition',
            field=models.TextField(blank=True, default='', verbose_name='Definition'),
        ),
        migrations.AlterField(
            model_name='parametercategory',
            name='definition',
            field=models.TextField(blank=True, default='', verbose_name='Definition'),
        ),
    ]
