# Generated by Django 3.1.6 on 2021-06-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0014_auto_20210330_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_uri',
            field=models.URLField(blank=True, default='', verbose_name='Station URI'),
        ),
    ]
