# Generated by Django 3.1.6 on 2021-06-29 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0015_station_station_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='waterway_uri',
        ),
    ]
