# Generated by Django 3.1.6 on 2021-07-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0016_remove_station_waterway_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='symbol',
            field=models.CharField(default='', max_length=200, verbose_name='Symbol'),
            preserve_default=False,
        ),
    ]
