# Generated by Django 3.1.5 on 2021-02-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_river'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='Network', max_length=100, verbose_name='Name'),
        ),
    ]
