# Generated by Django 3.1.14 on 2023-02-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_datasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attachment_link',
            field=models.URLField(blank=True, verbose_name='Picture URL'),
        ),
    ]
