# Generated by Django 3.1.14 on 2023-02-23 15:41

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_datasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attachment_link',
            field=models.URLField(blank=True, verbose_name='Picture URL'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachment_video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Video URL'),
        ),
    ]
