# Generated by Django 3.1.14 on 2023-03-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0016_auto_20220324_1419'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0009_auto_20230223_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceToSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(default=0, verbose_name='Distance')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='river.stream')),
            ],
            options={
                'verbose_name': 'Distance to source',
                'verbose_name_plural': 'Distance to sources',
                'unique_together': {('content_type', 'object_id', 'stream')},
            },
        ),
    ]
