# Generated by Django 3.1.14 on 2023-06-02 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_distancetosource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='User that uploaded', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
