# Generated by Django 3.1.14 on 2023-10-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_generate_distancetosource'),
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS unaccent;')
    ]
