# Generated by Django 3.1.5 on 2021-02-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vegetation',
            name='other_information',
            field=models.TextField(blank=True, verbose_name='Other information'),
        ),
        migrations.AlterField(
            model_name='vegetation',
            name='specific_variety',
            field=models.TextField(blank=True, verbose_name='Specific variety'),
        ),
        migrations.AlterField(
            model_name='vegetation',
            name='state',
            field=models.TextField(blank=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='work',
            name='material',
            field=models.TextField(blank=True, verbose_name='Materials'),
        ),
        migrations.AlterField(
            model_name='work',
            name='mobility',
            field=models.TextField(blank=True, verbose_name='Mobility'),
        ),
        migrations.AlterField(
            model_name='work',
            name='state',
            field=models.TextField(blank=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='work',
            name='usage',
            field=models.TextField(blank=True, verbose_name='Usage'),
        ),
    ]
