# Generated by Django 3.1.6 on 2021-09-15 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_auto_20210914_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='knowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='knowledge.knowledge', verbose_name='Knowledge'),
        ),
        migrations.AlterField(
            model_name='followupmeasure',
            name='follow_up',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='knowledge.followup', verbose_name='Follow-up'),
        ),
    ]
