# Generated by Django 3.1.6 on 2021-10-12 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_auto_20211012_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStreamInfluence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'Work stream influence',
                'verbose_name_plural': 'Work stream influences',
            },
        ),
        migrations.AlterField(
            model_name='work',
            name='downstream_bank_effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downstream_effect_works', to='knowledge.workbankeffect', verbose_name='Bank effect'),
        ),
        migrations.AlterField(
            model_name='work',
            name='fish_continuity_effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='knowledge.workfishcontinuityeffect', verbose_name='Fish Continuity effect'),
        ),
        migrations.AlterField(
            model_name='work',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='knowledge.workmaterial', verbose_name='Work material'),
        ),
        migrations.AlterField(
            model_name='work',
            name='sediment_effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='knowledge.worksedimenteffect', verbose_name='Sediment effect'),
        ),
        migrations.AlterField(
            model_name='work',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='knowledge.workstate', verbose_name='Work state'),
        ),
        migrations.AlterField(
            model_name='work',
            name='upstream_bank_effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upstream_effect_works', to='knowledge.workbankeffect', verbose_name='Upstream bank effect'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='knowledge.worktype', verbose_name='Work type'),
        ),
        migrations.AlterField(
            model_name='work',
            name='downstream_influence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downstream_effect_works', to='knowledge.workstreaminfluence', verbose_name='Downsteam influence'),
        ),
        migrations.AlterField(
            model_name='work',
            name='upstream_influence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upstream_effect_works', to='knowledge.workstreaminfluence', verbose_name='Upstream influence'),
        ),
    ]
