# Generated by Django 3.1.6 on 2021-10-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0010_auto_20211012_0838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkDownStreamInfluence',
        ),
        migrations.DeleteModel(
            name='WorkUpStreamInfluence',
        ),
    ]
