# Generated by Django 3.1.14 on 2023-05-15 14:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='max_zoom',
            field=models.PositiveSmallIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='portal',
            name='min_zoom',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portal',
            name='spatial_extent',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=2154),
        ),
        migrations.AlterField(
            model_name='portal',
            name='description',
            field=models.TextField(default='', help_text='Description on Georiviere website used for Search Engine Optimization', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='title',
            field=models.CharField(default='', help_text='Title on Georiviere website used for Search Engine Optimization', max_length=50, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='MapGroupLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.portal', verbose_name='Portal')),
            ],
            options={
                'verbose_name': 'Map group',
                'verbose_name_plural': 'Map groups',
                'ordering': ('label',),
                'unique_together': {('label', 'portal')},
            },
        ),
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('layer_type', models.CharField(editable=False, max_length=50, verbose_name='Layer type')),
                ('default_active', models.BooleanField(default=False)),
                ('style', models.JSONField(blank=True, default=dict, help_text='Style of the layer', max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('group_layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layers', to='portal.mapgrouplayer', verbose_name='Map group layers')),
                ('portal', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='layers', to='portal.portal', verbose_name='Portal')),
            ],
            options={
                'verbose_name': 'Map layer',
                'verbose_name_plural': 'Map layers',
                'ordering': ('label',),
                'unique_together': {('label', 'order', 'group_layer')},
            },
        ),
        migrations.CreateModel(
            name='MapBaseLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('url', models.CharField(blank=True, help_text='URL', max_length=255)),
                ('min_zoom', models.PositiveSmallIntegerField(default=0)),
                ('max_zoom', models.PositiveSmallIntegerField(default=22)),
                ('attribution', models.CharField(blank=True, help_text='Attribution of the baselayer. Example : © OpenStreetMap', max_length=255)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='map_base_layers', to='portal.portal', verbose_name='Portal')),
            ],
            options={
                'verbose_name': 'Map base layer',
                'verbose_name_plural': 'Map base layers',
                'ordering': ('label',),
                'unique_together': {('label', 'portal')},
            },
        ),
    ]
