# Generated by Django 3.1.14 on 2023-05-03 15:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapBaseLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('url', models.CharField(blank=True, help_text='URL', max_length=255)),
                ('min_zoom', models.PositiveSmallIntegerField(default=0)),
                ('max_zoom', models.PositiveSmallIntegerField(default=22)),
                ('attribution', models.CharField(blank=True, help_text="Attribution of the baselayer. Example : '© OpenStreetMap", max_length=255)),
                ('bounds', models.CharField(blank=True, help_text='Bounds', max_length=255)),
            ],
            options={
                'verbose_name': 'Map base layer',
                'verbose_name_plural': 'Map base layers',
                'ordering': ('label',),
            },
        ),
        migrations.AddField(
            model_name='portal',
            name='max_zoom',
            field=models.PositiveSmallIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='portal',
            name='min_zoom',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portal',
            name='spatial_extent',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=2154),
        ),
        migrations.CreateModel(
            name='MapOverlayLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('url', models.CharField(help_text='URL of the layer', max_length=255, unique=True)),
                ('default_active', models.BooleanField(default=False)),
                ('style', models.JSONField(default=dict, help_text='Style of the layer', max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Map overlay layer',
                'verbose_name_plural': 'Map overlay layers',
                'ordering': ('label',),
                'unique_together': {('label', 'order')},
            },
        ),
        migrations.CreateModel(
            name='MapOverlayGroupLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('layers', models.ManyToManyField(to='portal.MapOverlayLayer', verbose_name='Overlay layers')),
            ],
            options={
                'verbose_name': 'Map overlay group',
                'verbose_name_plural': 'Map overlay groups',
                'ordering': ('label',),
            },
        ),
        migrations.AddField(
            model_name='portal',
            name='map_base_layers',
            field=models.ManyToManyField(to='portal.MapBaseLayer', verbose_name='Map base layers'),
        ),
        migrations.AddField(
            model_name='portal',
            name='map_group_overlay_layers',
            field=models.ManyToManyField(to='portal.MapOverlayGroupLayer', verbose_name='Map group overlay layers'),
        ),
    ]
