# Generated by Django 3.1.14 on 2023-05-15 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20230515_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplayer',
            name='group_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layers', to='portal.mapgrouplayer', verbose_name='Map group layer'),
        ),
    ]
