# Generated by Django 3.1.14 on 2023-05-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20230515_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
