# Generated by Django 3.1.14 on 2023-05-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_maplayer_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplayer',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
