# Generated by Django 3.1.14 on 2024-04-29 12:33

from django.db import migrations
from django.utils.translation import gettext_lazy as _


def add_custom_contributions_map_layer_to_portals(apps, schema_editor):
    MapLayer = apps.get_model("portal", "MapLayer")
    Portal = apps.get_model("portal", "Portal")

    for portal in Portal.objects.all():
        MapLayer.objects.create(
            portal=portal,
            layer_type="contributions-custom",
            label=_("Custom contributions"),
            hidden=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_auto_20240423_1647"),
    ]

    operations = [
        migrations.RunPython(
            add_custom_contributions_map_layer_to_portals, reverse_code=migrations.RunPython.noop
        ),
    ]
