# Generated by Django 3.1.6 on 2021-02-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_auto_20210215_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_type',
            field=models.CharField(choices=[('HYDRO', 'Hydrometric station'), ('TEMP', 'Temperature station'), ('PCQAL', 'Physic-chimic quality station')], default='HYDRO', max_length=5, verbose_name='Station type'),
        ),
    ]
