# Generated by Django 3.1.6 on 2021-03-29 08:44

from django.db import migrations, models
import django.db.models.deletion
import geotrek.authent.models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0005_remove_userprofile_language'),
        ('observations', '0010_auto_20210322_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Label')),
                ('definition', models.TextField(blank=True, null=True, verbose_name='Definition')),
                ('parameter_type', models.IntegerField(choices=[(1, 'Qualitative'), (2, 'Quantitative')], default=2, verbose_name='Parameter type')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=200, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='ParameterTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Label')),
                ('measure_frequency', models.CharField(max_length=200, verbose_name='Measure frequency')),
                ('transmission_frequency', models.CharField(max_length=200, verbose_name='Transmission frequency')),
                ('data_availability', models.IntegerField(blank=True, choices=[(1, 'Online'), (2, 'On demand')], null=True, verbose_name='Data availability')),
                ('measure_start_date', models.DateField(verbose_name='Measure start date')),
                ('measure_end_date', models.DateField(verbose_name='Measure end date')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.parameter', verbose_name='Parameter')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.station', verbose_name='Station')),
                ('structure', models.ForeignKey(default=geotrek.authent.models.default_structure_pk, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure')),
            ],
            options={
                'verbose_name': 'Parameter tracking',
                'verbose_name_plural': 'Parameter trackings',
            },
        ),
        migrations.CreateModel(
            name='ParameterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Label')),
                ('definition', models.TextField(blank=True, null=True, verbose_name='Definition')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure')),
            ],
            options={
                'verbose_name': 'Parameter category',
                'verbose_name_plural': 'Parameter categories',
            },
        ),
        migrations.AddField(
            model_name='parameter',
            name='categories',
            field=models.ManyToManyField(related_name='parameters', to='observations.ParameterCategory'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.unit', verbose_name='Unit'),
        ),
    ]
