# Generated by Django 3.1.6 on 2021-08-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0019_auto_20210722_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ['label'], 'verbose_name': 'Parameter', 'verbose_name_plural': 'Parameters'},
        ),
        migrations.AlterModelOptions(
            name='parametercategory',
            options={'ordering': ['label'], 'verbose_name': 'Parameter category', 'verbose_name_plural': 'Parameter categories'},
        ),
        migrations.AlterModelOptions(
            name='parametertracking',
            options={'ordering': ['parameter'], 'verbose_name': 'Parameter tracking', 'verbose_name_plural': 'Parameter trackings'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['label'], 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
    ]
