# Generated by Django 3.1.4 on 2020-12-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('LAND', 'Land'), ('REFERENCIAL', 'Referencial'), ('USAGE', 'Usage')], default='PHYSICAL', max_length=11),
        ),
    ]
