# Generated by Django 3.1.7 on 2021-03-02 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0005_auto_20210222_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Flow type',
                'verbose_name_plural': 'Flow types',
            },
        ),
        migrations.CreateModel(
            name='IncisionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Incision type',
                'verbose_name_plural': 'Incision types',
            },
        ),
        migrations.CreateModel(
            name='SedimentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Sediment type',
                'verbose_name_plural': 'Sediment types',
            },
        ),
        migrations.CreateModel(
            name='WidthType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Width type',
                'verbose_name_plural': 'Width types',
            },
        ),
        migrations.RemoveField(
            model_name='morphology',
            name='category',
        ),
        migrations.RemoveField(
            model_name='morphology',
            name='morphology_type',
        ),
        migrations.DeleteModel(
            name='MorphologyCategory',
        ),
        migrations.AddField(
            model_name='morphology',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='description.flowtype', verbose_name='Flow'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='incision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='description.incisiontype', verbose_name='Incision'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='primary_sediment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_sediment', to='description.sedimenttype', verbose_name='Primary sediment'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='secondary_sediment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_sediment', to='description.sedimenttype', verbose_name='Secondary sediment'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='width',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='description.widthtype', verbose_name='Width'),
        ),
    ]
