# Generated by Django 3.1.6 on 2021-03-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0008_auto_20210322_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='usage_type',
        ),
        migrations.AddField(
            model_name='usage',
            name='usage_types',
            field=models.ManyToManyField(to='description.UsageType', verbose_name='Usage types'),
        ),
    ]
