# Generated by Django 3.1.6 on 2021-04-21 08:54

import django.contrib.gis.db.models.fields
from django.db import migrations

from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0014_generate_topologies_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morphology',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=settings.SRID),
        ),
        migrations.AlterField(
            model_name='status',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=settings.SRID),
        ),
    ]
