# Generated by Django 3.1.6 on 2021-05-31 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0015_auto_20210421_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morphology',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='status',
            name='structure',
        ),
    ]
