# Generated by Django 3.1.6 on 2021-09-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0018_auto_20210901_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landtype',
            options={'ordering': ['label'], 'verbose_name': 'Land type', 'verbose_name_plural': 'Land types'},
        ),
        migrations.AlterModelOptions(
            name='statustype',
            options={'ordering': ['label'], 'verbose_name': 'Status type', 'verbose_name_plural': 'Status types'},
        ),
        migrations.AlterModelOptions(
            name='usagetype',
            options={'ordering': ['label'], 'verbose_name': 'Usage type', 'verbose_name_plural': 'Usage types'},
        ),
        migrations.RenameField(
            model_name='bankstate',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='faciesdiversity',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='flowtype',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='granulometricdiversity',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='habitatsdiversity',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='habitattype',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='landtype',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='planlayouttype',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='sedimentdynamic',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='statustype',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='usagetype',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='workingspacetype',
            old_name='name',
            new_name='label',
        ),
    ]
