# Generated by Django 3.1.14 on 2022-12-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0020_auto_20210901_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='morphology',
            name='secondary_flows',
            field=models.ManyToManyField(blank=True, related_name='morphologies_on_second', to='description.FlowType', verbose_name='Secondary flow'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='secondary_habitats',
            field=models.ManyToManyField(blank=True, related_name='morphologies_on_second', to='description.HabitatType', verbose_name='Secondary habitat'),
        ),
    ]
