# Generated by Django 3.1.14 on 2022-12-13 11:04

from django.db import migrations


def migrate_secondary_flow_habitat(apps, schema_editor):
    MorphologyModel = apps.get_model('description', 'Morphology')
    morphologies_with_secondary_flow = MorphologyModel.objects.filter(secondary_flow__isnull=False)
    for morphology in morphologies_with_secondary_flow:
        morphology.secondary_flows.add(morphology.secondary_flow)
        morphology.save()
    morphologies_with_secondary_habitat = MorphologyModel.objects.filter(secondary_habitat__isnull=False)
    for morphology in morphologies_with_secondary_habitat:
        morphology.secondary_habitats.add(morphology.secondary_habitat)
        morphology.save()


def reverse_migrate_secondary_flow_habitat(apps, schema_editor):
    MorphologyModel = apps.get_model('description', 'Morphology')
    morphologies_with_secondary_flow = MorphologyModel.objects.filter(secondary_flow__isnull=False)
    for morphology in morphologies_with_secondary_flow:
        morphology.secondary_flow = morphology.secondary_flows.first()
        morphology.save()
    morphologies_with_secondary_habitat = MorphologyModel.objects.filter(secondary_habitat__isnull=False)
    for morphology in morphologies_with_secondary_habitat:
        morphology.secondary_habitat = morphology.secondary_habitats.first()
        morphology.save()


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0021_auto_20221213_1104'),
    ]

    operations = [
        migrations.RunPython(migrate_secondary_flow_habitat, reverse_migrate_secondary_flow_habitat)
    ]
