# Generated by Django 3.1.14 on 2023-03-23 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0005_remove_userprofile_language'),
        ('description', '0023_auto_20221213_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, unique=True, verbose_name='Label')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure')),
            ],
            options={
                'verbose_name': 'Control type',
                'verbose_name_plural': 'Control types',
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='land',
            name='control_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='description.controltype', verbose_name='Control type'),
        ),
    ]
