# Generated by Django 3.1.14 on 2023-12-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0024_auto_20230323_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='morphology',
            name='user',
            field=models.TextField(null=True),
        ),
    ]
