# Generated by Django 3.1.14 on 2023-12-18 12:22

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0025_auto_20231215_1124'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='land',
            name='keep_in_sync',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='morphology',
            name='keep_in_sync',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='status',
            name='keep_in_sync',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='usage',
            name='keep_in_sync',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='land',
            trigger=pgtrigger.compiler.Trigger(name='keep_in_sync', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE elevation elevation_infos;', func='\n                    SELECT * FROM ft_elevation_infos(NEW.geom, 20) INTO elevation;\n                    -- Update path geometry\n                    NEW.geom_3d := elevation.draped;\n                    NEW.length := ST_3DLength(elevation.draped);\n                    NEW.slope := elevation.slope;\n                    NEW.min_elevation := elevation.min_elevation;\n                    NEW.max_elevation := elevation.max_elevation;\n                    NEW.ascent := elevation.positive_gain;\n                    NEW.descent := elevation.negative_gain;\n                    RETURN NEW;\n                ', hash='d639f6850243942a05ed1f44f6cf79b88b563bad', operation='UPDATE OF "geom" OR INSERT', pgid='pgtrigger_keep_in_sync_fb8bb', table='description_land', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='morphology',
            trigger=pgtrigger.compiler.Trigger(name='keep_in_sync', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE elevation elevation_infos;', func='\n                    SELECT * FROM ft_elevation_infos(NEW.geom, 20) INTO elevation;\n                    -- Update path geometry\n                    NEW.geom_3d := elevation.draped;\n                    NEW.length := ST_3DLength(elevation.draped);\n                    NEW.slope := elevation.slope;\n                    NEW.min_elevation := elevation.min_elevation;\n                    NEW.max_elevation := elevation.max_elevation;\n                    NEW.ascent := elevation.positive_gain;\n                    NEW.descent := elevation.negative_gain;\n                    RETURN NEW;\n                ', hash='048fe3697643f7682b5336def02a2a9d345947ae', operation='UPDATE OF "geom" OR INSERT', pgid='pgtrigger_keep_in_sync_472ec', table='description_morphology', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='status',
            trigger=pgtrigger.compiler.Trigger(name='keep_in_sync', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE elevation elevation_infos;', func='\n                    SELECT * FROM ft_elevation_infos(NEW.geom, 20) INTO elevation;\n                    -- Update path geometry\n                    NEW.geom_3d := elevation.draped;\n                    NEW.length := ST_3DLength(elevation.draped);\n                    NEW.slope := elevation.slope;\n                    NEW.min_elevation := elevation.min_elevation;\n                    NEW.max_elevation := elevation.max_elevation;\n                    NEW.ascent := elevation.positive_gain;\n                    NEW.descent := elevation.negative_gain;\n                    RETURN NEW;\n                ', hash='967fa66b6c8eb5e17d5bfc49594c2573241d073b', operation='UPDATE OF "geom" OR INSERT', pgid='pgtrigger_keep_in_sync_aa87c', table='description_status', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usage',
            trigger=pgtrigger.compiler.Trigger(name='keep_in_sync', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE elevation elevation_infos;', func='\n                    SELECT * FROM ft_elevation_infos(NEW.geom, 20) INTO elevation;\n                    -- Update path geometry\n                    NEW.geom_3d := elevation.draped;\n                    NEW.length := ST_3DLength(elevation.draped);\n                    NEW.slope := elevation.slope;\n                    NEW.min_elevation := elevation.min_elevation;\n                    NEW.max_elevation := elevation.max_elevation;\n                    NEW.ascent := elevation.positive_gain;\n                    NEW.descent := elevation.negative_gain;\n                    RETURN NEW;\n                ', hash='69cb0cd06f0dccdca1f09d54169f5a673b87fca5', operation='UPDATE OF "geom" OR INSERT', pgid='pgtrigger_keep_in_sync_71b71', table='description_usage', when='BEFORE')),
        ),
    ]
