# Generated by Django 3.1.14 on 2023-12-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0025_morphology_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morphology',
            name='user',
        ),
    ]
