# Generated by Django 3.1.14 on 2023-12-22 16:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0026_remove_morphology_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineMorphology',
            fields=[
                ('uuid', models.TextField(primary_key=True, serialize=False)),
                ('gra_id', models.IntegerField(null=True)),
                ('stream_name', models.TextField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=2154)),
                ('qualified', models.BooleanField(null=True)),
                ('good_working_space_left', models.IntegerField(null=True)),
                ('good_working_space_right', models.IntegerField(null=True)),
                ('facies_diversity', models.IntegerField(null=True)),
                ('main_flow', models.IntegerField(null=True)),
                ('granulometric_diversity', models.IntegerField(null=True)),
                ('full_edge_height', models.FloatField(default=0.0, null=True)),
                ('full_edge_width', models.FloatField(default=0.0, null=True)),
                ('sediment_dynamic', models.IntegerField(null=True)),
                ('bank_state_left', models.IntegerField(null=True)),
                ('bank_state_right', models.IntegerField(null=True)),
                ('habitats_diversity', models.IntegerField(null=True)),
                ('main_habitat', models.IntegerField(null=True)),
                ('plan_layout', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('date_insert', models.DateTimeField(null=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('username', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineSecondaryFlow',
            fields=[
                ('uuid', models.TextField(primary_key=True, serialize=False)),
                ('morphology_uuid', models.TextField(null=True)),
                ('flow_type_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineSecondaryHabitat',
            fields=[
                ('uuid', models.TextField(primary_key=True, serialize=False)),
                ('morphology_uuid', models.TextField(null=True)),
                ('habitat_type_id', models.IntegerField(null=True)),
            ],
        ),
    ]
