# Generated by Django 3.1.4 on 2020-12-09 14:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models

from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('type', models.CharField(choices=[('Physical', 'PHYSICAL'), ('Land', 'LAND'), ('Referencial', 'REFERENCIAL'), ('usage', 'USAGE')], default='PHYSICAL', max_length=11)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(spatial_index=False, srid=settings.SRID)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
