# Generated by Django 3.1.6 on 2021-02-15 15:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
import geotrek.zoning.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0003_auto_20210125_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom_3d', django.contrib.gis.db.models.fields.GeometryField(default=None, dim=3, editable=False, null=True, spatial_index=False, srid=settings.SRID)),
                ('length', models.FloatField(blank=True, default=0.0, editable=False, null=True, verbose_name='3D Length')),
                ('ascent', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Ascent')),
                ('descent', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Descent')),
                ('min_elevation', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Minimum elevation')),
                ('max_elevation', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Maximum elevation')),
                ('slope', models.FloatField(blank=True, default=0.0, editable=False, null=True, verbose_name='Slope')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=settings.SRID)),
                ('owner', models.TextField(blank=True, verbose_name='Owner')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Land',
                'verbose_name_plural': 'Lands',
            },
            bases=(geotrek.zoning.mixins.ZoningPropertiesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LandType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Land type',
                'verbose_name_plural': 'Land types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Morphology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom_3d', django.contrib.gis.db.models.fields.GeometryField(default=None, dim=3, editable=False, null=True, spatial_index=False, srid=settings.SRID)),
                ('length', models.FloatField(blank=True, default=0.0, editable=False, null=True, verbose_name='3D Length')),
                ('ascent', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Ascent')),
                ('descent', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Descent')),
                ('min_elevation', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Minimum elevation')),
                ('max_elevation', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Maximum elevation')),
                ('slope', models.FloatField(blank=True, default=0.0, editable=False, null=True, verbose_name='Slope')),
                ('morphology_type', models.CharField(choices=[('FLOW', 'Flow'), ('SEDIMENT', 'Sediment'), ('WIDTH', 'Width'), ('INCISION', 'Incision')], db_index=True, max_length=128, verbose_name='Morphology type')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=settings.SRID)),
            ],
            options={
                'verbose_name': 'Morphology',
                'verbose_name_plural': 'Morphologies',
            },
            bases=(geotrek.zoning.mixins.ZoningPropertiesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MorphologyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Morphology type',
                'verbose_name_plural': 'Morphology types',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom_3d', django.contrib.gis.db.models.fields.GeometryField(default=None, dim=3, editable=False, null=True, spatial_index=False, srid=settings.SRID)),
                ('length', models.FloatField(blank=True, default=0.0, editable=False, null=True, verbose_name='3D Length')),
                ('ascent', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Ascent')),
                ('descent', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Descent')),
                ('min_elevation', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Minimum elevation')),
                ('max_elevation', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Maximum elevation')),
                ('slope', models.FloatField(blank=True, default=0.0, editable=False, null=True, verbose_name='Slope')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=settings.SRID)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
            bases=(geotrek.zoning.mixins.ZoningPropertiesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Status type',
                'verbose_name_plural': 'Status types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom_3d', django.contrib.gis.db.models.fields.GeometryField(default=None, dim=3, editable=False, null=True, spatial_index=False, srid=settings.SRID)),
                ('length', models.FloatField(blank=True, default=0.0, editable=False, null=True, verbose_name='3D Length')),
                ('ascent', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Ascent')),
                ('descent', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Descent')),
                ('min_elevation', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Minimum elevation')),
                ('max_elevation', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Maximum elevation')),
                ('slope', models.FloatField(blank=True, default=0.0, editable=False, null=True, verbose_name='Slope')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=settings.SRID)),
            ],
            options={
                'verbose_name': 'Usage',
                'verbose_name_plural': 'Usages',
            },
            bases=(geotrek.zoning.mixins.ZoningPropertiesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UsageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Usage type',
                'verbose_name_plural': 'Usage types',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.AddField(
            model_name='usage',
            name='usage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='description.usagetype', verbose_name='Usage type'),
        ),
        migrations.AddField(
            model_name='status',
            name='status_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='description.statustype', verbose_name='Status type'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='description.morphologycategory', verbose_name='Morphology category'),
        ),
        migrations.AddField(
            model_name='land',
            name='land_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='description.landtype', verbose_name='Land type'),
        ),
    ]
