# Generated by Django 3.1.6 on 2021-02-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0004_auto_20210215_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='referencial',
            field=models.BooleanField(default=False, help_text='Your status is a referencial status', verbose_name='Referencial'),
        ),
        migrations.AddField(
            model_name='status',
            name='regulation',
            field=models.BooleanField(default=False, help_text='Your status is a regulation status', verbose_name='Regulation'),
        ),
    ]
