# Generated by Django 3.1.6 on 2021-03-30 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0005_remove_userprofile_language'),
        ('description', '0010_auto_20210322_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure')),
            ],
            options={
                'verbose_name': 'Bank state',
                'verbose_name_plural': 'Bank states',
            },
        ),
        migrations.CreateModel(
            name='FaciesDiversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure')),
            ],
            options={
                'verbose_name': 'Facies diversity',
                'verbose_name_plural': 'Facies diversities',
            },
        ),
        migrations.CreateModel(
            name='GranulometricDiversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure')),
            ],
            options={
                'verbose_name': 'Granulometric diversity',
                'verbose_name_plural': 'Granulometric diversities',
            },
        ),
        migrations.CreateModel(
            name='HabitatsDiversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure')),
            ],
            options={
                'verbose_name': 'Habitats diversity',
                'verbose_name_plural': 'Habitats diversities',
            },
        ),
        migrations.CreateModel(
            name='HabitatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure')),
            ],
            options={
                'verbose_name': 'Habitat type',
                'verbose_name_plural': 'Habitat types',
            },
        ),
        migrations.CreateModel(
            name='PlanLayoutType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure')),
            ],
            options={
                'verbose_name': 'Plan layout type',
                'verbose_name_plural': 'Plan layout types',
            },
        ),
        migrations.CreateModel(
            name='SedimentDynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure')),
            ],
            options={
                'verbose_name': 'Sediment dynamic',
                'verbose_name_plural': 'Sediment dynamics',
            },
        ),
        migrations.CreateModel(
            name='WorkingSpaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure')),
            ],
            options={
                'verbose_name': 'Working space type',
                'verbose_name_plural': 'Working space types',
            },
        ),
        migrations.RemoveField(
            model_name='sedimenttype',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='widthtype',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='morphology',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='morphology',
            name='incision',
        ),
        migrations.RemoveField(
            model_name='morphology',
            name='primary_sediment',
        ),
        migrations.RemoveField(
            model_name='morphology',
            name='secondary_sediment',
        ),
        migrations.RemoveField(
            model_name='morphology',
            name='width',
        ),
        migrations.AddField(
            model_name='morphology',
            name='full_edge_height',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Full edge height'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='full_edge_width',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Full edge width'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='main_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_flow', to='description.flowtype', verbose_name='Main flow'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='secondary_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_flow', to='description.flowtype', verbose_name='Secondary flow'),
        ),
        migrations.DeleteModel(
            name='IncisionType',
        ),
        migrations.DeleteModel(
            name='SedimentType',
        ),
        migrations.DeleteModel(
            name='WidthType',
        ),
        migrations.AddField(
            model_name='morphology',
            name='bank_state_left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_state_left', to='description.bankstate', verbose_name='Bank state left'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='bank_state_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_state_right', to='description.bankstate', verbose_name='Bank state right'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='facies_diversity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facies_diversity', to='description.faciesdiversity', verbose_name='Facies diversity'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='good_working_space_left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='good_working_space_left', to='description.workingspacetype', verbose_name='Left good Working space'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='good_working_space_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='good_working_space_right', to='description.workingspacetype', verbose_name='Right good Working space'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='granulometric_diversity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='description.granulometricdiversity', verbose_name='Granulometric diversity'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='habitats_diversity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='description.habitatsdiversity', verbose_name='Habitats diversity'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='main_habitat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_habitat', to='description.habitattype', verbose_name='Main habitat'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='plan_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='description.planlayouttype', verbose_name='Plan layout'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='secondary_habitat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_habitat', to='description.habitattype', verbose_name='Secondary habitat'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='sediment_dynamic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='description.sedimentdynamic', verbose_name='Sediment dynamic'),
        ),
    ]
