# Generated by Django 3.1.6 on 2021-04-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0007_topology'),
        ('description', '0012_remove_morphology_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='morphology',
            name='topology',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='morphology', to='river.topology'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='topology',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='river.topology'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='status_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='description.statustype', verbose_name='Status type'),
        ),
    ]
