# Generated by Django 3.1.6 on 2021-06-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0016_auto_20210531_0857'),
        ('description', '0016_auto_20210602_0857'),
    ]

    operations = [
    ]
