# Generated by Django 3.1.14 on 2023-04-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_insert', models.DateTimeField(auto_now_add=True, verbose_name='Insertion date')),
                ('date_update', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update date')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('external_url', models.URLField(blank=True, default='', help_text='Link to external website instead of HTML content', verbose_name='External URL')),
                ('content', models.TextField(blank=True, help_text='HTML content', null=True, verbose_name='Content')),
                ('order', models.IntegerField(blank=True, default=None, help_text='ID order if blank', null=True, unique=True, verbose_name='Order')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('portals', models.ManyToManyField(blank=True, related_name='flatpages', to='portal.Portal', verbose_name='Published portals')),
            ],
            options={
                'verbose_name': 'Flat page',
                'verbose_name_plural': 'Flat pages',
                'ordering': ['order', 'id'],
                'permissions': (('read_flatpage', 'Can read FlatPage'),),
            },
        ),
        migrations.CreateModel(
            name='FlatPagePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_insert', models.DateTimeField(auto_now_add=True, verbose_name='Insertion date')),
                ('date_update', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update date')),
                ('picture', models.FileField(max_length=512, null=True, upload_to='flatpages', verbose_name='Pictogram')),
                ('flatpage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to='flatpages.flatpage')),
            ],
            options={
                'verbose_name': 'Flat page picture',
                'verbose_name_plural': 'Flat page pictures',
            },
        ),
    ]
