# Generated by Django 3.1.14 on 2023-06-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0002_contribution_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionpotentialdamage',
            name='landing_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contribution.landingtype', verbose_name='Landing type'),
        ),
        migrations.AlterField(
            model_name='contributionpotentialdamage',
            name='length_bank_erosion',
            field=models.FloatField(blank=True, default=0.0, help_text='Distance between the foot of the bank and the foot of the erosion.', null=True, verbose_name='Length bank erosion'),
        ),
    ]
