# Generated by Django 3.1.14 on 2023-07-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0004_auto_20230724_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='validated',
            field=models.BooleanField(default=False, help_text='Validate the contribution', verbose_name='Validated'),
        ),
    ]
