# Generated by Django 3.1.14 on 2023-07-25 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('contribution', '0006_contribution_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='linked_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='linked_object_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
