# Generated by Django 3.1.14 on 2023-07-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0007_auto_20230725_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionfaunaflora',
            name='home_area',
            field=models.FloatField(blank=True, default=0.0, help_text='Home area in square meters', null=True, verbose_name='Home area (in square meters)'),
        ),
        migrations.AlterField(
            model_name='contributionpotentialdamage',
            name='bank_height',
            field=models.FloatField(blank=True, default=0.0, help_text='Bank height (measured between the foot of the bank and the top of the bank) in meters', null=True, verbose_name='Bank height (in meters)'),
        ),
        migrations.AlterField(
            model_name='contributionpotentialdamage',
            name='excessive_cutting_length',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Excessive cutting length (in meters)'),
        ),
        migrations.AlterField(
            model_name='contributionpotentialdamage',
            name='length_bank_erosion',
            field=models.FloatField(blank=True, default=0.0, help_text='Distance between the foot of the bank and the foot of the erosion.', null=True, verbose_name='Length bank erosion (in meters)'),
        ),
    ]
