# Generated by Django 3.1.14 on 2023-11-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0008_auto_20230731_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingtype',
            options={'verbose_name': 'Landing type', 'verbose_name_plural': 'Landing types'},
        ),
    ]
