# Generated by Django 3.1.14 on 2024-04-11 08:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20230915_1756'),
        ('contribution', '0009_auto_20231110_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomContributionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, unique=True, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'Custom contribution type',
                'verbose_name_plural': 'Custom contribution types',
            },
        ),
        migrations.CreateModel(
            name='CustomContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_insert', models.DateTimeField(auto_now_add=True, verbose_name='Insertion date')),
                ('date_update', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update date')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=2154)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('validated', models.BooleanField(default=False, verbose_name='Validated')),
                ('custom_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='contribution.customcontributiontype')),
                ('portal', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_contributions', to='portal.portal', verbose_name='Portal')),
            ],
            options={
                'verbose_name': 'Custom contribution',
                'verbose_name_plural': 'Custom contributions',
            },
        ),
        migrations.CreateModel(
            name='CustomContributionTypeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
                ('key', models.SlugField(editable=False, help_text='Key used in JSON field', max_length=150, verbose_name='Type')),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('float', 'Float'), ('date', 'Date'), ('datetime', 'Datetime'), ('boolean', 'Boolean')], default='text', max_length=16, verbose_name='Label')),
                ('required', models.BooleanField(default=False, verbose_name='Required')),
                ('options', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('custom_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='contribution.customcontributiontype')),
            ],
            options={
                'verbose_name': 'Custom contribution type field',
                'verbose_name_plural': 'Custom contribution type fields',
                'unique_together': {('label', 'custom_type')},
            },
        ),
    ]
