# Generated by Django 3.1.14 on 2024-04-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0010_customcontribution_customcontributiontype_customcontributiontypefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcontributiontypefield',
            name='key',
            field=models.SlugField(editable=False, help_text='Key used in JSON field', max_length=150, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='customcontributiontypefield',
            name='value_type',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('float', 'Float'), ('date', 'Date'), ('datetime', 'Datetime'), ('boolean', 'Boolean')], default='text', max_length=16, verbose_name='Type'),
        ),
    ]
