# Generated by Django 3.1.14 on 2024-04-11 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20230915_1756'),
        ('contribution', '0011_auto_20240411_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcontribution',
            name='portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_contributions', to='portal.portal', verbose_name='Portal'),
        ),
    ]
