# Generated by Django 3.1.14 on 2024-04-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0012_auto_20240411_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcontributiontype',
            name='linked_to_station',
            field=models.BooleanField(default=False, verbose_name='Linked to station'),
        ),
    ]
