# Generated by Django 3.1.14 on 2024-04-12 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0023_auto_20230220_1703'),
        ('contribution', '0014_auto_20240412_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcontribution',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_contributions', to='observations.station', verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='customcontributiontypefield',
            name='value_type',
            field=models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('integer', 'Integer'), ('float', 'Float'), ('date', 'Date'), ('datetime', 'Datetime'), ('boolean', 'Boolean')], default='string', max_length=16, verbose_name='Type'),
        ),
    ]
