# Generated by Django 3.1.14 on 2024-04-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0015_auto_20240412_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customcontributiontype',
            options={'ordering': ('label',), 'verbose_name': 'Custom contribution type', 'verbose_name_plural': 'Custom contribution types'},
        ),
        migrations.AddField(
            model_name='customcontributiontype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Description'),
        ),
    ]
