# Generated by Django 3.1.14 on 2024-04-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0023_auto_20230220_1703'),
        ('contribution', '0016_auto_20240423_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcontributiontype',
            name='stations',
            field=models.ManyToManyField(blank=True, related_name='custom_contribution_types', to='observations.Station', verbose_name='Stations'),
        ),
    ]
