# Generated by Django 3.1.14 on 2024-04-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0018_auto_20240425_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcontributiontypefield',
            name='internal_identifier',
            field=models.CharField(blank=True, help_text='Internal identifier for field.', max_length=128, null=True, unique=True, verbose_name='Internal identifier'),
        ),
        migrations.AlterField(
            model_name='customcontributiontypefield',
            name='label',
            field=models.CharField(help_text='Field label in forms and public portal.', max_length=128, verbose_name='Label'),
        ),
        migrations.AlterUniqueTogether(
            name='customcontributiontypefield',
            unique_together={('label', 'custom_type'), ('internal_identifier', 'custom_type')},
        ),
    ]
