# Generated by Django 3.1.5 on 2021-02-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='River',
        ),
    ]
