# Generated by Django 3.1.6 on 2021-03-03 10:07

from django.db import migrations, models
import django.db.models.deletion
import geotrek.authent.models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0005_remove_userprofile_language'),
        ('main', '0004_auto_20210202_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filetype',
            options={'verbose_name': 'Related structures', 'verbose_name_plural': 'Related structure'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Related structures', 'verbose_name_plural': 'Related structure'},
        ),
        migrations.AddField(
            model_name='filetype',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure'),
        ),
        migrations.AddField(
            model_name='network',
            name='structure',
            field=models.ForeignKey(default=geotrek.authent.models.default_structure_pk, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure'),
        ),
        migrations.AddField(
            model_name='tag',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure'),
        ),
    ]
