# Generated by Django 3.1.6 on 2021-03-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210303_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='structure',
        ),
        migrations.DeleteModel(
            name='Network',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
