# Generated by Django 3.1.14 on 2023-08-09 12:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watershed', '0002_watershedtype_portals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watershedtype',
            name='color',
            field=colorfield.fields.ColorField(default='#444444', help_text='Color shown on map of Georiviere-admin', max_length=18, verbose_name='Color'),
        ),
    ]
