# Generated by Django 3.1.6 on 2021-02-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0002_auto_20210201_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='river',
            options={'verbose_name': 'Stream', 'verbose_name_plural': 'Streams'},
        ),
        migrations.AlterField(
            model_name='river',
            name='name',
            field=models.CharField(default='Stream', max_length=100, verbose_name='Name'),
        ),
    ]
