# Generated by Django 3.1.6 on 2021-02-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0003_auto_20210209_1533'),
    ]

    operations = [
        migrations.RenameModel('River', 'Stream')
    ]
