# Generated by Django 3.1.6 on 2021-09-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20210802_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventiondisorder',
            name='label',
            field=models.CharField(max_length=128, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='interventionstake',
            name='label',
            field=models.CharField(max_length=128, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='interventionstatus',
            name='label',
            field=models.CharField(max_length=128, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='interventiontype',
            name='label',
            field=models.CharField(max_length=128, verbose_name='Label'),
        ),
    ]
