# Generated by Django 3.1.6 on 2021-04-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0007_topology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='downstream',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='upstream',
        ),
    ]
