# Generated by Django 3.1.6 on 2021-09-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0009_auto_20210421_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='width',
        ),
    ]
