# Generated by Django 3.1.6 on 2021-10-28 09:06

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0010_remove_stream_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='source_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=settings.SRID, verbose_name='Source location'),
        ),
    ]
