# Generated by Django 3.1.14 on 2022-03-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0013_auto_20220117_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='flow',
            field=models.CharField(choices=[(0, 'To be defined'), (1, 'Permanent'), (2, 'Temporary')], default=0, max_length=2, verbose_name='Flow'),
        ),
    ]
