# Generated by Django 3.1.14 on 2022-03-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0015_stream_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='flow',
            field=models.IntegerField(blank=True, choices=[(0, 'To be defined'), (1, 'Permanent'), (2, 'Temporary')], default=0, verbose_name='Flow'),
        ),
    ]
