# Generated by Django 3.1.14 on 2023-04-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        ('river', '0017_auto_20230327_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='portals',
            field=models.ManyToManyField(blank=True, related_name='streams', to='portal.Portal', verbose_name='Published portals'),
        ),
    ]
