# Generated by Django 3.1.14 on 2023-05-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0018_stream_portals'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
