# Generated by Django 3.1.14 on 2023-12-15 10:51

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0020_auto_20231215_1020'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='stream',
            name='keep_in_sync',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stream',
            trigger=pgtrigger.compiler.Trigger(name='keep_in_sync', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE elevation elevation_infos;', func='\n                    SELECT * FROM ft_elevation_infos(NEW.geom, 20) INTO elevation;\n                    -- Update path geometry\n                    NEW.geom_3d := element.draped;\n                    NEW.length := ST_3DLength(element.draped);\n                    NEW.slope := element.slope;\n                    NEW.min_elevation := element.min_elevation;\n                    NEW.max_elevation := element.max_elevation;\n                    NEW.ascent := element.positive_gain;\n                    NEW.descent := element.negative_gain;\n\n                    RETURN NEW;\n                ', hash='fdeef3b3432dda345b1ec896b91e84eb120a9986', operation='UPDATE OR INSERT', pgid='pgtrigger_keep_in_sync_7a86b', table='river_stream', when='BEFORE')),
        ),
    ]
