# Generated by Django 3.1.14 on 2023-12-15 10:56

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0022_auto_20231215_1052'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='stream',
            name='keep_in_sync',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stream',
            trigger=pgtrigger.compiler.Trigger(name='keep_in_sync', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE elevation elevation_infos;', func='\n                    SELECT * FROM ft_elevation_infos(NEW.geom, 20) INTO elevation;\n                    -- Update path geometry\n                    NEW.geom_3d := elevation.draped;\n                    NEW.length := ST_3DLength(elevation.draped);\n                    NEW.slope := elevation.slope;\n                    NEW.min_elevation := elevation.min_elevation;\n                    NEW.max_elevation := elevation.max_elevation;\n                    NEW.ascent := elevation.positive_gain;\n                    NEW.descent := elevation.negative_gain;\n\n                    RETURN NEW;\n                ', hash='168b84532fa3b4230f53fbd1cfdb1169c5d72a0a', operation='UPDATE OF "geom" OR INSERT', pgid='pgtrigger_keep_in_sync_7a86b', table='river_stream', when='BEFORE')),
        ),
    ]
