# Generated by Django 3.1.14 on 2023-12-18 12:26

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0023_auto_20231215_1056'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='stream',
            name='keep_in_sync',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stream',
            trigger=pgtrigger.compiler.Trigger(name='keep_in_sync', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE elevation elevation_infos;', func='\n                    SELECT * FROM ft_elevation_infos(NEW.geom, 20) INTO elevation;\n                    -- Update path geometry\n                    NEW.geom_3d := elevation.draped;\n                    NEW.length := ST_3DLength(elevation.draped);\n                    NEW.slope := elevation.slope;\n                    NEW.min_elevation := elevation.min_elevation;\n                    NEW.max_elevation := elevation.max_elevation;\n                    NEW.ascent := elevation.positive_gain;\n                    NEW.descent := elevation.negative_gain;\n                    RETURN NEW;\n                ', hash='e66f827b3e0e2d3e5f822a259752f2d8a48a7c26', operation='UPDATE OF "geom" OR INSERT', pgid='pgtrigger_keep_in_sync_7a86b', table='river_stream', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='topology',
            trigger=pgtrigger.compiler.Trigger(name='update_topology_geom', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE elevation elevation_infos; geom geometry;', func='\n                    IF (NEW.start_point != OLD.start_point OR NEW.end_point != OLD.end_point) THEN \n                        SELECT geom FROM river_stream r WHERE NEW.id = r.id INTO geom;\n                        UPDATE description_morphology\n                        SET geom = ST_LINESUBSTRING(geom, NEW.START_POINT, NEW.END_POINT)\n                        WHERE topology_id = NEW.id; \n                        UPDATE description_status\n                        SET geom = ST_LINESUBSTRING(geom, NEW.START_POINT, NEW.END_POINT)\n                        WHERE topology_id = NEW.id; \n                    END IF;\n                    RETURN NEW;\n                ', hash='db1df9343d9079232a59df61b34bfcd7bc2df48a', operation='UPDATE OR INSERT', pgid='pgtrigger_update_topology_geom_011ed', table='river_topology', when='BEFORE')),
        ),
    ]
