# Generated by Django 3.1.14 on 2023-12-18 13:56

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0025_auto_20231218_1325'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='topology',
            name='update_topology_geom',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='topology',
            trigger=pgtrigger.compiler.Trigger(name='update_topology_geom', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE elevation elevation_infos; geom geometry;', func='\n                    IF (NEW.start_position != OLD.start_position OR NEW.end_position != OLD.end_position) THEN \n                        SELECT geom FROM river_stream r WHERE NEW.id = r.id INTO geom;\n                        UPDATE description_morphology\n                        SET geom = ST_LINESUBSTRING(geom, NEW.start_position, NEW.end_position)\n                        WHERE topology_id = NEW.id; \n                        UPDATE description_status\n                        SET geom = ST_LINESUBSTRING(geom, NEW.start_position, NEW.end_position)\n                        WHERE topology_id = NEW.id; \n                    END IF;\n                    RETURN NEW;\n                ', hash='10d2e4894631bee97f91deeb607004d3a5295448', operation='UPDATE OR INSERT', pgid='pgtrigger_update_topology_geom_011ed', table='river_topology', when='BEFORE')),
        ),
    ]
