# Generated by Django 3.1.14 on 2023-12-18 14:00

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0026_auto_20231218_1356'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='stream',
            name='create_topologies',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stream',
            trigger=pgtrigger.compiler.Trigger(name='create_topologies', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE topology_morphology integer; topology_status integer;', func='\n                        INSERT INTO river_topology (stream_id, start_position, end_position, qualified)\n                        VALUES (NEW.id, 0, 1, FALSE)  RETURNING id INTO topology_morphology;\n                        INSERT INTO description_morphology (topology_id, geom) VALUES (topology_morphology, NEW.geom);\n                        INSERT INTO river_topology (stream_id, start_position, end_position, qualified)\n                        VALUES (NEW.id, 0, 1, FALSE)  RETURNING id INTO topology_status;\n                        INSERT INTO description_status (topology_id, geom) VALUES (topology_status, NEW.geom);\n                        RETURN NEW;\n                    ', hash='4ebe61234dd666bf424de96761a8af7e0a72560f', operation='INSERT', pgid='pgtrigger_create_topologies_e8d7d', table='river_stream', when='AFTER')),
        ),
    ]
