# Generated by Django 3.1.14 on 2023-12-18 14:10

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0031_auto_20231218_1405'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='stream',
            trigger=pgtrigger.compiler.Trigger(name='update_topologies', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                                UPDATE river_topology SET start_position=start_position WHERE stream_id=NEW.id;\n                                RETURN NEW;\n                            ', hash='0b6322b6b455eed7b6a2a78c79b07e08e9a86611', operation='UPDATE OF "geom"', pgid='pgtrigger_update_topologies_6ab45', table='river_stream', when='AFTER')),
        ),
    ]
