# Generated by Django 3.1.14 on 2023-12-18 14:16

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0033_auto_20231218_1412'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='topology',
            name='update_topology_geom',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='topology',
            trigger=pgtrigger.compiler.Trigger(name='update_topology_geom', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE elevation elevation_infos; geom geometry;', func='\n                        SELECT r.geom FROM river_stream r WHERE NEW.id = r.id INTO geom;\n                        UPDATE description_morphology\n                        SET geom = ST_LINESUBSTRING(geom, NEW.start_position, NEW.end_position)\n                        WHERE topology_id = NEW.id; \n                        UPDATE description_status\n                        SET geom = ST_LINESUBSTRING(geom, NEW.start_position, NEW.end_position)\n                        WHERE topology_id = NEW.id; \n                    RETURN NEW;\n                ', hash='1e3e1dbd526ffd01e8155aec62fad614e188471d', operation='UPDATE OR INSERT', pgid='pgtrigger_update_topology_geom_011ed', table='river_topology', when='BEFORE')),
        ),
    ]
