# Generated by Django 3.1.14 on 2023-12-18 14:18

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0034_auto_20231218_1416'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='topology',
            name='update_topology_geom',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='topology',
            trigger=pgtrigger.compiler.Trigger(name='update_topology_geom', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE elevation elevation_infos; geom geometry;', func='\n                        SELECT r.geom FROM river_stream r WHERE NEW.id = r.id INTO geom;\n                        UPDATE description_morphology m\n                        SET m.geom = ST_LINESUBSTRING(geom, NEW.start_position, NEW.end_position)\n                        WHERE topology_id = NEW.id; \n                        UPDATE description_status s\n                        SET s.geom = ST_LINESUBSTRING(geom, NEW.start_position, NEW.end_position)\n                        WHERE topology_id = NEW.id; \n                    RETURN NEW;\n                ', hash='a3d43086e66e04cde5bf979df1f4565a3bb9e791', operation='UPDATE OR INSERT', pgid='pgtrigger_update_topology_geom_011ed', table='river_topology', when='BEFORE')),
        ),
    ]
