# Generated by Django 3.1.14 on 2023-12-18 16:01

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0038_auto_20231218_1431'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='stream',
            name='update_topologies',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stream',
            trigger=pgtrigger.compiler.Trigger(name='update_topologies', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                                UPDATE river_topology SET id=id WHERE stream_id=NEW.id;\n                                RETURN NEW;\n                            ', hash='704192b93012d12fa95b06b03618981a49609a4e', operation='UPDATE OF "geom"', pgid='pgtrigger_update_topologies_6ab45', table='river_stream', when='AFTER')),
        ),
    ]
