# Generated by Django 3.1.14 on 2023-04-20 11:30

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import georiviere.main.models
import geotrek.authent.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
        ('authent', '0005_remove_userprofile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='POIActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_insert', models.DateTimeField(auto_now_add=True, verbose_name='Insertion date')),
                ('date_update', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update date')),
                ('label', models.CharField(max_length=128, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'POI action type',
                'verbose_name_plural': 'POI action types',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='POIKnowledgeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_insert', models.DateTimeField(auto_now_add=True, verbose_name='Insertion date')),
                ('date_update', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update date')),
                ('label', models.CharField(max_length=128, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'POI knowledge type',
                'verbose_name_plural': 'POI knowledge types',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='POIKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_insert', models.DateTimeField(auto_now_add=True, verbose_name='Insertion date')),
                ('date_update', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update date')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='History, details,  ...', verbose_name='Description')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=settings.SRID)),
                ('portals', models.ManyToManyField(blank=True, related_name='poi_knowledges', to='portal.Portal', verbose_name='Portals')),
                ('structure', models.ForeignKey(default=geotrek.authent.models.default_structure_pk, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='valorization.poiknowledgetype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'POI knowledge',
                'verbose_name_plural': 'POIs knowledge ',
            },
            bases=(georiviere.main.models.AddPropertyBufferMixin, models.Model),
        ),
        migrations.CreateModel(
            name='POIAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_insert', models.DateTimeField(auto_now_add=True, verbose_name='Insertion date')),
                ('date_update', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update date')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='History, details,  ...', verbose_name='Description')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=settings.SRID)),
                ('portals', models.ManyToManyField(blank=True, related_name='poi_actions', to='portal.Portal', verbose_name='Portals')),
                ('structure', models.ForeignKey(default=geotrek.authent.models.default_structure_pk, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='valorization.poiactiontype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'POI action',
                'verbose_name_plural': 'POIs action',
            },
            bases=(georiviere.main.models.AddPropertyBufferMixin, models.Model),
        ),
    ]
