# Generated by Django 3.1.14 on 2023-05-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitype',
            name='pictogram',
            field=models.FileField(max_length=512, null=True, upload_to='upload', verbose_name='Pictogram'),
        ),
    ]
