# Generated by Django 3.1.14 on 2023-05-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0005_remove_userprofile_language'),
        ('valorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poi',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='poitype',
            unique_together={('label', 'structure', 'category')},
        ),
    ]
