# Generated by Django 3.1.14 on 2023-04-24 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0005_remove_userprofile_language'),
        ('valorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poiactiontype',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure'),
        ),
        migrations.AddField(
            model_name='poiknowledgetype',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure'),
        ),
        migrations.AlterField(
            model_name='poiaction',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pois', to='valorization.poiactiontype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='poiknowledge',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pois', to='valorization.poiknowledgetype', verbose_name='Type'),
        ),
        migrations.AlterUniqueTogether(
            name='poiactiontype',
            unique_together={('label', 'structure')},
        ),
        migrations.AlterUniqueTogether(
            name='poiknowledgetype',
            unique_together={('label', 'structure')},
        ),
    ]
