# Generated by Django 3.1.14 on 2023-05-15 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valorization', '0002_poitype_pictogram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poicategory',
            options={'ordering': ['label'], 'verbose_name': 'POI Category', 'verbose_name_plural': 'POI Categories'},
        ),
    ]
