# Generated by Django 3.1.14 on 2024-05-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valorization', '0003_auto_20230515_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='external_uri',
            field=models.URLField(blank=True, default='', verbose_name='POI link'),
        ),
    ]
