# Generated by Django 3.1.6 on 2021-02-11 14:18

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Station code')),
                ('label', models.CharField(max_length=200, verbose_name='Station label')),
                ('description', models.TextField(blank=True, default='', verbose_name='Station description')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=settings.SRID)),
                ('site_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Site code')),
                ('waterway_uri', models.URLField(blank=True, default='', verbose_name='Waterway URI')),
                ('purpose_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Station purpose')),
                ('in_service', models.BooleanField(blank=True, default=False, verbose_name='In service')),
                ('station_type', models.CharField(choices=[('HYDRO', 'Hydrometric station'), ('TEMP', 'Temperature station'), ('PCQAL', 'Physic-chimic quality station')], default='HYDRO', max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
