# Generated by Django 3.1.6 on 2021-03-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_auto_20210316_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='station_type',
        ),
    ]
