# Generated by Django 3.1.6 on 2021-03-30 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0005_remove_userprofile_language'),
        ('observations', '0012_remove_station_altitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametertracking',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure'),
        ),
    ]
