# Generated by Django 3.1.6 on 2021-07-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0017_unit_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='code',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametercategory',
            name='code',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parametertracking',
            name='measure_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Measure end date'),
        ),
        migrations.AlterField(
            model_name='parametertracking',
            name='measure_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Measure start date'),
        ),
    ]
