# Generated by Django 3.1.6 on 2021-07-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0018_auto_20210721_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametertracking',
            name='label',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='parametertracking',
            name='measure_frequency',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Measure frequency'),
        ),
        migrations.AlterField(
            model_name='parametertracking',
            name='transmission_frequency',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Transmission frequency'),
        ),
    ]
