# Generated by Django 3.1.13 on 2022-02-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0021_auto_20210901_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='local_influence',
            field=models.IntegerField(blank=True, choices=[(0, 'Unknown'), (1, 'Null'), (2, 'Low water only'), (3, 'Strong'), (4, 'High water only')], default=0, help_text='For hydrometric station profile', verbose_name='Local influence'),
        ),
    ]
