# Generated by Django 3.1.14 on 2023-02-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0022_auto_20220207_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='annex_uri',
            field=models.URLField(blank=True, default='', verbose_name='Annex URI'),
        ),
        migrations.AddField(
            model_name='station',
            name='operations_uri',
            field=models.URLField(blank=True, default='', verbose_name='Operations URI'),
        ),
    ]
