# Generated by Django 3.1.6 on 2021-04-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='study_type',
        ),
        migrations.AddField(
            model_name='study',
            name='study_types',
            field=models.ManyToManyField(to='studies.StudyType', verbose_name='Study types'),
        ),
    ]
