# Generated by Django 3.1.6 on 2021-08-04 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0005_remove_userprofile_language'),
        ('proceeding', '0002_auto_20210624_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='proceeding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='proceeding.proceeding', verbose_name='Proceeding'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure'),
        ),
    ]
