# Generated by Django 3.1.6 on 2021-10-20 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances_administration', '0004_jobcategory_manday'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeoperation',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='manday',
            name='job_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandays', to='finances_administration.jobcategory', verbose_name='Job category'),
        ),
        migrations.AlterField(
            model_name='manday',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandays', to='finances_administration.administrativeoperation', verbose_name='Operation'),
        ),
    ]
