# Generated by Django 3.1.13 on 2021-12-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances_administration', '0007_auto_20211020_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeoperation',
            name='manday_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Cost of man-day'),
        ),
    ]
