# Generated by Django 3.1.6 on 2021-06-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0015_auto_20210421_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='status_type',
        ),
        migrations.AddField(
            model_name='status',
            name='status_types',
            field=models.ManyToManyField(blank=True, related_name='status', to='description.StatusType', verbose_name='Status type'),
        ),
    ]
