# Generated by Django 3.1.6 on 2021-09-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0019_auto_20210901_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstate',
            name='label',
            field=models.CharField(max_length=128, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='faciesdiversity',
            name='label',
            field=models.CharField(max_length=128, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='flowtype',
            name='label',
            field=models.CharField(max_length=128, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='granulometricdiversity',
            name='label',
            field=models.CharField(max_length=128, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='habitatsdiversity',
            name='label',
            field=models.CharField(max_length=128, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='habitattype',
            name='label',
            field=models.CharField(max_length=128, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='landtype',
            name='label',
            field=models.CharField(max_length=128, unique=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='planlayouttype',
            name='label',
            field=models.CharField(max_length=128, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='sedimentdynamic',
            name='label',
            field=models.CharField(max_length=128, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='label',
            field=models.CharField(max_length=128, unique=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='usagetype',
            name='label',
            field=models.CharField(max_length=128, unique=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='workingspacetype',
            name='label',
            field=models.CharField(max_length=128, verbose_name='Label'),
        ),
    ]
