# Generated by Django 3.1.6 on 2021-08-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances_administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeoperation',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Estimated cost'),
        ),
        migrations.AddField(
            model_name='administrativeoperation',
            name='material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Material cost'),
        ),
        migrations.AddField(
            model_name='administrativeoperation',
            name='subcontract_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Subcontract cost'),
        ),
        migrations.AlterField(
            model_name='administrativefile',
            name='global_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Global cost'),
        ),
    ]
