# Generated by Django 3.1.6 on 2021-09-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances_administration', '0002_auto_20210825_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativefile',
            name='global_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Global cost'),
        ),
        migrations.AlterField(
            model_name='administrativeoperation',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Estimated cost'),
        ),
        migrations.AlterField(
            model_name='administrativeoperation',
            name='material_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Material cost'),
        ),
        migrations.AlterField(
            model_name='administrativeoperation',
            name='subcontract_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Subcontract cost'),
        ),
    ]
