# Generated by Django 3.1.6 on 2021-10-19 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0005_remove_userprofile_language'),
        ('finances_administration', '0003_auto_20210907_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
                ('man_day_cost', models.DecimalField(decimal_places=2, default=1.0, max_digits=8, verbose_name='Cost of man-day')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure')),
            ],
            options={
                'verbose_name': 'Job category',
                'verbose_name_plural': 'Job categories',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='ManDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_days', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Man-days')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances_administration.jobcategory', verbose_name='Job category')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances_administration.administrativeoperation')),
            ],
            options={
                'verbose_name': 'Man-day',
                'verbose_name_plural': 'Man-days',
            },
        ),
    ]
