# Generated by Django 3.1.6 on 2021-10-20 14:18

from decimal import Decimal
from django.db import migrations
from django.db.models import F, Sum


def update_manday_cost(apps, schema_editor):
    """Update manday_cost with computed value"""
    AdministrativeOperation = apps.get_model('finances_administration', 'AdministrativeOperation')
    for operation in AdministrativeOperation.objects.all():
        if operation.mandays.count():
            result = operation.mandays \
                .annotate(cost=F('nb_days') * F('job_category__man_day_cost')) \
                .aggregate(total=Sum('cost'))
            operation.manday_cost = result['total'].quantize(Decimal('1.00'))
            operation.save()


def reset_manday_cost(apps, schema_editor):
    """Reverse operation : reset manday_cost to zero"""
    AdministrativeOperation = apps.get_model('finances_administration', 'AdministrativeOperation')
    for operation in AdministrativeOperation.objects.all():
        operation.manday_cost = Decimal('0.00')
        operation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('finances_administration', '0006_administrativeoperation_manday_cost'),
    ]

    operations = [
        migrations.RunPython(update_manday_cost, reset_manday_cost),
    ]
