# Generated by Django 3.1.4 on 2020-12-09 14:25

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import paperclip.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, verbose_name='File type')),
            ],
            options={
                'verbose_name': 'File type',
                'verbose_name_plural': 'File types',
                'ordering': ['type'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Network', max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(spatial_index=False, srid=settings.SRID)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='River', max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(spatial_index=False, srid=settings.SRID)),
                ('upstream', models.FloatField(db_index=True, null=True, verbose_name='Start position')),
                ('downstream', models.FloatField(db_index=True, null=True, verbose_name='End position')),
                ('width', models.FloatField(default=3.14159, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('attachment_file', models.FileField(blank=True, max_length=512, upload_to=paperclip.models.attachment_upload, verbose_name='File')),
                ('author', models.CharField(blank=True, db_column='auteur', default='', help_text='Original creator', max_length=128, verbose_name='Author')),
                ('title', models.CharField(blank=True, db_column='titre', default='', help_text='Renames the file', max_length=128, verbose_name='Filename')),
                ('legend', models.CharField(blank=True, db_column='legende', default='', help_text='Details displayed', max_length=128, verbose_name='Legend')),
                ('starred', models.BooleanField(db_column='marque', default=False, help_text='Mark as starred', verbose_name='Starred')),
                ('is_image', models.BooleanField(db_index=True, default=False, editable=False, help_text='Is an image file', verbose_name='Is image')),
                ('date_insert', models.DateTimeField(auto_now_add=True, verbose_name='Insertion date')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('creator', models.ForeignKey(help_text='User that uploaded', on_delete=django.db.models.deletion.CASCADE, related_name='created_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('filetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.filetype', verbose_name='File type')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-date_insert'],
                'permissions': (('add_attachment', 'Can add attachments'), ('change_attachment', 'Can change attachments'), ('delete_attachment', 'Can delete attachments'), ('read_attachment', 'Can read attachments'), ('delete_attachment_others', "Can delete others' attachments")),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
