# Generated by Django 3.1.6 on 2021-03-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210329_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filetype',
            options={'ordering': ['type'], 'verbose_name': 'File type', 'verbose_name_plural': 'File types'},
        ),
    ]
