# Generated by Django 3.1.6 on 2021-08-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervention',
            old_name='geom',
            new_name='_geom',
        ),
        migrations.AddField(
            model_name='intervention',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='target_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
