# Generated by Django 3.1.13 on 2021-11-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_auto_20210901_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='length',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Length'),
        ),
    ]
