# Generated by Django 3.1.14 on 2023-12-21 09:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_intervention_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineIntervention',
            fields=[
                ('uuid', models.TextField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=2154)),
                ('knowledge_uuid', models.TextField(null=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('date', models.DateField(null=True)),
                ('intervention_status', models.IntegerField(null=True)),
                ('intervention_type', models.IntegerField(null=True)),
                ('stake', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('length', models.FloatField(default=0.0, null=True)),
                ('width', models.FloatField(default=0.0, null=True)),
                ('height', models.FloatField(default=0.0, null=True)),
                ('date_insert', models.DateTimeField(null=True)),
                ('date_update', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineInterventionDisorder',
            fields=[
                ('uuid', models.TextField(primary_key=True, serialize=False)),
                ('disorder_id', models.IntegerField(null=True)),
                ('intervention_uuid', models.TextField(null=True)),
            ],
        ),
    ]
