# Generated by Django 3.1.14 on 2023-12-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_offlineintervention_offlineinterventiondisorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineintervention',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
