# Generated by Django 3.1.14 on 2023-12-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_offlineintervention_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineintervention',
            name='gra_id',
            field=models.IntegerField(null=True),
        ),
    ]
