# Generated by Django 3.1.6 on 2021-06-15 13:56

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import geotrek.authent.models
import geotrek.zoning.mixins
import georiviere.watershed.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authent', '0005_remove_userprofile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom_3d', django.contrib.gis.db.models.fields.GeometryField(default=None, dim=3, editable=False, null=True, spatial_index=False, srid=settings.SRID)),
                ('length', models.FloatField(blank=True, default=0.0, editable=False, null=True, verbose_name='3D Length')),
                ('ascent', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Ascent')),
                ('descent', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Descent')),
                ('min_elevation', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Minimum elevation')),
                ('max_elevation', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Maximum elevation')),
                ('slope', models.FloatField(blank=True, default=0.0, editable=False, null=True, verbose_name='Slope')),
                ('date_insert', models.DateTimeField(auto_now_add=True, verbose_name='Insertion date')),
                ('date_update', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update date')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('eid', models.CharField(blank=True, max_length=1024, null=True, verbose_name='External id')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=settings.SRID)),
                ('structure', models.ForeignKey(default=geotrek.authent.models.default_structure_pk, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure')),
            ],
            options={
                'abstract': False,
            },
            bases=(georiviere.watershed.mixins.WatershedPropertiesMixin, geotrek.zoning.mixins.ZoningPropertiesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('structure', models.ForeignKey(default=geotrek.authent.models.default_structure_pk, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure')),
            ],
            options={
                'verbose_name': 'Event type',
                'verbose_name_plural': 'Event types',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proceeding.eventtype', verbose_name='Event type')),
                ('proceeding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='proceeding.proceeding', verbose_name='Proceeding')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
