# Generated by Django 3.1.6 on 2021-06-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proceeding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proceeding',
            options={'verbose_name': 'Proceeding', 'verbose_name_plural': 'Proceedings'},
        ),
    ]
