# Generated by Django 3.1.14 on 2023-12-15 11:24

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proceeding', '0003_auto_20210804_1014'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='proceeding',
            trigger=pgtrigger.compiler.Trigger(name='keep_in_sync', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE elevation elevation_infos;', func='\n                    SELECT * FROM ft_elevation_infos(NEW.geom, 20) INTO elevation;\n                    -- Update path geometry\n                    NEW.geom_3d := elevation.draped;\n                    NEW.length := ST_3DLength(elevation.draped);\n                    NEW.slope := elevation.slope;\n                    NEW.min_elevation := elevation.min_elevation;\n                    NEW.max_elevation := elevation.max_elevation;\n                    NEW.ascent := elevation.positive_gain;\n                    NEW.descent := elevation.negative_gain;\n\n                    RETURN NEW;\n                ', hash='4580ed3c25a4cd5a156ff3a0c1efd6c8301d8e25', operation='UPDATE OF "geom" OR INSERT', pgid='pgtrigger_keep_in_sync_6ba14', table='proceeding_proceeding', when='BEFORE')),
        ),
    ]
