# Generated by Django 3.1.14 on 2023-12-18 12:22

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proceeding', '0004_auto_20231215_1124'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='proceeding',
            name='keep_in_sync',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='proceeding',
            trigger=pgtrigger.compiler.Trigger(name='keep_in_sync', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE elevation elevation_infos;', func='\n                    SELECT * FROM ft_elevation_infos(NEW.geom, 20) INTO elevation;\n                    -- Update path geometry\n                    NEW.geom_3d := elevation.draped;\n                    NEW.length := ST_3DLength(elevation.draped);\n                    NEW.slope := elevation.slope;\n                    NEW.min_elevation := elevation.min_elevation;\n                    NEW.max_elevation := elevation.max_elevation;\n                    NEW.ascent := elevation.positive_gain;\n                    NEW.descent := elevation.negative_gain;\n                    RETURN NEW;\n                ', hash='8be1e3d34cf0ef421d9f1750b10e7ef296d6a20d', operation='UPDATE OF "geom" OR INSERT', pgid='pgtrigger_keep_in_sync_6ba14', table='proceeding_proceeding', when='BEFORE')),
        ),
    ]
