# Generated by Django 3.1.5 on 2021-02-01 13:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='River', max_length=100, verbose_name='Name')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=settings.SRID)),
                ('upstream', models.FloatField(db_index=True, null=True, verbose_name='Start position')),
                ('downstream', models.FloatField(db_index=True, null=True, verbose_name='End position')),
                ('width', models.FloatField(default=1, help_text='In meters', null=True, verbose_name='Width')),
            ],
            options={
                'verbose_name': 'River',
                'verbose_name_plural': 'Rivers',
            },
        ),
    ]
