# Generated by Django 3.1.5 on 2021-02-01 13:40

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='river',
            name='ascent',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Ascent'),
        ),
        migrations.AddField(
            model_name='river',
            name='descent',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Descent'),
        ),
        migrations.AddField(
            model_name='river',
            name='geom_3d',
            field=django.contrib.gis.db.models.fields.GeometryField(default=None, dim=3, editable=False, null=True, spatial_index=False, srid=settings.SRID),
        ),
        migrations.AddField(
            model_name='river',
            name='length',
            field=models.FloatField(blank=True, default=0.0, editable=False, null=True, verbose_name='3D Length'),
        ),
        migrations.AddField(
            model_name='river',
            name='max_elevation',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Maximum elevation'),
        ),
        migrations.AddField(
            model_name='river',
            name='min_elevation',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Minimum elevation'),
        ),
        migrations.AddField(
            model_name='river',
            name='slope',
            field=models.FloatField(blank=True, default=0.0, editable=False, null=True, verbose_name='Slope'),
        ),
    ]
