# Generated by Django 3.1.6 on 2021-04-13 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0006_stream_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_position', models.FloatField(db_index=True, default=0, verbose_name='Start position')),
                ('end_position', models.FloatField(db_index=True, default=1, verbose_name='End position')),
                ('qualified', models.BooleanField(default=False, verbose_name='Qualified')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='river.stream', verbose_name='Stream')),
            ],
            options={
                'verbose_name': 'Topology',
                'verbose_name_plural': 'Topologies',
            },
        ),
    ]
